### ISSUE TITLE
2020.0.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [ksh-community/ksh#12]
All is on https://github.com/att/ast/issues/1478

PS. Any plans to make forst release?

**Comment by kloczek** [comment]
Closing.

Looks like that projet has nothing to do with work which has been done recently on ksh.
A bit disapointing ..

**Comment by marcastel** [comment]
@kloczek A bit frustrating to see issues opened and closed within a couple of minutes, and questions answered within the same time lapse by the originating author. I would have been tempted to delete this issue altogether, but then we would have lost the prime motivation on you initial visit to this project.

We are all committed to have a working KornShell in all environments. So could you please elaborate on your requirements?

The 2020 version you mention is a solo initiative by some which unfortunately weared the AT&T hat while not being supported in any way by AT&T. Nor are we for that matter. Our difference is in our name; we are a community edition where the community is important.

So, as a KornShell user, if you have important feedback relative to the existence and use of a `ksh93u+` compatible KornShell in your environment, please take the time to notify us, in so far that this does not relate to an unsupported KornShell with a unsupported build system (at least by us).

**Comment by kloczek** [comment]
It is a bit frustrating to see abandonedo meson and other things which are now now allow reproduce the same effect.

Is it any plan to reintroduce meson files here?

**Comment by marcastel** [comment]
@kloczek I fully understand your frustration as a user depending on a package that fails.

No, meson is not on our roadmap.

Our initial steps as a new community will be to ensure that all environments have a working copy of `ksh93u+`; consider this as a take over of the maintenance of the last official version of the KornShell delivered by AT&T.

In this respect, changing the build system, is all but a priority. The importance is that the product gets built. How it is built is of secondary or even tertiary importance.

I have already [given my opinion](https://github.com/att/ast/issues/42) on the build system. This opinion is not necessarily shared. Time will come to discuss this. But not now.

**Comment by kloczek** [comment]
> No, meson is not on our roadmap.

Why? So it will be necessary again sit upside down on chair to have ksh with LTO/PGO? :/

To be honest I don't care about Self Adoration Society aka "community". I care only about the code.

PS. I'm really disappointed now that some programmers do not understand how important is to have proper build framework.

**Comment by marcastel** [comment]
@kloczek If your topic is to theorise on a build system, by my guest, elsewhere, a this is not among the immediate tasks we have to solve here.

But please share if you have KornShell specific comments, suggestions, or even if you want to share the workload this community is putting in _after hours_.

Otherwise I suggest we do indeed close this issue.

**Comment by kloczek** [comment]
Issue is that As long as I've been using completely different method on testing that ticket is a bit useless and to be honest it is a bit discouraging to even try to reproduce that as long as there is no here proper build framework. Do you see my point?

It was very good reason to use meson. As long as that part is already done pushing that on the bottom of the ToDo list is rally hard to understand.

Proper build framework like meson based will allow easy build and test it on many OS types with %100. reuse of the build procedure and testing it with different compiler, optimisation or with coverage or  other quality control code filters/tools. Do you see that now? Without that quite quickly will be wasted tenths times more time on trying retest ksh in different contexts.

**Comment by marcastel** [comment]
@kloczek I don't see your point. But happy to discuss it elsewhere.

I have created [this issue](https://github.com/marcastel/kornshell-build-system/issues/1) if you want to discuss this further. And obviously anybody interested is welcome.

In the meantime I will close this issue here. In due time we can reopen it :-)

**Comment by jghub** [comment]
as @marcastel already pointed out, reinstating meson as build system is currently not under consideration. we _are_ considering to also support cmake in the future. and I do not agree that the build system in itself is really of much relevance. what +is+ relevant is that ksh93 builds everywhere (again). there also are/were several people objecting against meson. personally, I simply do not care too much as long as it builds easily. 

please also note that we were not involved in and  have not stopped ksh2020. the one to two guys behind that effort have stopped it (for the time being or forever: I have no idea) when ATT for good reasons did no longer grant them the opportunity to pretend they were maintaining the "real" ksh93 "officially". I am _very_ happy about ATT's decision.

as you can find out yourself by reading through the issues in the ATT ksh repo (if you care...) ksh2020 has had *lots* of trouble and was doing harm to stability and compatibility and performance relative to ksh93u+ (at least that is my definitive assessment). so the rewind to ksh93u+ has been a "good thing" (™) in my view.

but if you do not really care for any of those issues and put more importance on the build system than on the shortcomings of ksh2020 relative to ksh93u+, this is fine with me. but it might then be better to try to get in touch with the guy(s) behind ksh2020...

**Comment by saper** [comment]
> LTO

Which linker would you like to use?

> PGO

How would you like to profile? Using the testsuite or some custom code?
