### ISSUE TITLE
Build Failure on FreeBSD

### ISSUE THREAD

**Issue by cschuber** [ksh-community/ksh#20]
On FreeBSD we get the following build failure:

# src/cmd/INIT/Mamfile: 32-35: make probe
+ cp probe.sh probe
+ u+w,+x probe
sh: u+w,+x: not found
mamake [cmd/INIT]: *** exit code 127 making probe
mamake: *** exit code 1 making cmd/INIT
mamake: *** exit code 1 making all
package: creating flat view
package: make failed at Wed Jun 26 06:14:31 PDT 2024 in /export/wrkdir/amd64/export/freebsd/git/ports/shells/ksh-devel/work/ksh-1407f3be/arch/freebsd15.i386-64
*** Error code 1

I've worked around the problem by add the environment variable STDCHMOD=chmod to the FreeBSD ports Makefile, but this is a hack until this can be better fixed.

**Comment by cschuber** [comment]
I discovered the problem. e8b45cc8 caused this regression the previous regression plus other regressions.

**Comment by McDutchie** [comment]
Thanks for the report but this is the wrong repo, please report at https://github.com/ksh93/ksh in future.

I cannot reproduce the build failure on FreeBSD, so I'm going to need more information.

**Comment by McDutchie** [comment]
Hey @cschuber, please close this as it's been resolved. Thanks.

**Comment by cschuber** [comment]
This has been fixed. Thanks.
